"""Turn the purchased ExerciseDB set into the map Forge reads.

    python tools/build_exercise_media.py "C:/Users/johnc.moore/Downloads/starter/starter" --copy

The set lives outside the repo on purpose. Keeping half a gigabyte of licensed GIFs inside the
project meant the dev server's file watcher opened the combined JSON while OneDrive held it
locked and took the whole process down; it is also one `git add -A` away from publishing the
library to a public repo. The path is an argument, so it can live anywhere.

The delivered set is one combined `exerciseData_*.json` plus `180/` and `360/` folders of
`<id>.gif`. Forge is keyed by slug, so this joins the two and writes
`src/data/exerciseMediaMap.ts`.

Names are the join, and the two vocabularies do not line up: Forge says "Conventional
Deadlift" where the catalogue says "barbell deadlift". Three passes, most certain first:

1. an alias somebody has checked by eye
2. an exact match on the normalised name
3. the Forge name appearing whole inside a catalogue name -- "bench press" inside "barbell
   bench press" -- where the equipment agrees

That last check is what the delivered data buys us over the sample. Every entry carries an
`equipment` field, so "Bench Press" can be held against *barbell* bench press and not against
the band one. Guessing from the words in the name, which is all the sample supported, put a
resistance band on a screen that said barbell.

Nothing is guessed beyond that. A wrong picture is worse than no picture -- somebody looking
up a movement they do not know has no way to tell they are being shown the wrong one -- so
anything ambiguous is left out and listed for review.

`--copy` also copies the matched 180px GIFs into `public/exercise-media/`, which the app
serves, and writes `exercise-media-review.html` at the repo root -- a contact sheet of every
picture beside the movement it was matched to. Reviewing pictures against a table of names is
the slow way to do it; the eye catches a farmer's walk on a suitcase carry in about a second.
Both are gitignored and must stay that way -- see the note in `data/exerciseMedia.ts`.

Only the matched GIFs are copied: the full set is 530 MB and Forge has uses for a fraction.

**`--copy` is superseded and should not be used to fill `public/exercise-media/`.** The app now
reads `<id>.webp`, produced for the whole referenced set by `tools/convert_exercise_media.py`,
and the reasoning in the second paragraph above no longer holds: a Capacitor build has to carry
its pictures, so "a fraction" is not an option. Copying GIFs in now leaves files nothing reads,
sitting beside the ones that matter. The matching in this file is still the only thing that
produces `exerciseMediaMap.ts` for the curated library, so run it without `--copy`.
"""

import io
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SEED = os.path.join(ROOT, "src", "data", "seed", "exercises.ts")
OUT = os.path.join(ROOT, "src", "data", "exerciseMediaMap.ts")
REVIEW = os.path.join(ROOT, "docs", "exercise-media-review.md")
MEDIA = os.path.join(ROOT, "public", "exercise-media")
SHEET = os.path.join(ROOT, "exercise-media-review.html")

#: Written out rather than escaped: this file is generated by a script that is itself
#: generated, and a backslash has not survived that round trip yet.
CRLF = chr(13) + chr(10)

#: Which size ships. The info sheet draws at 180 CSS pixels; 360 costs about three times the
#: bytes, which is not worth it for a reference picture.
SIZE = "180"

#: Forge slug -> the catalogue's name for the same movement, or its four-digit id.
#:
#: Only pairs somebody has looked at. Extend this from the contact sheet the script writes.
#:
#: An id is for when a name cannot pick one entry out: "hyperextension" and "hyperextension
#: (on bench)" normalise to the same string, and which of the two you get would otherwise
#: depend on their order in the file.
ALIASES = {
    "bench-press": "barbell bench press",
    "db-bench-press": "dumbbell bench press",
    "deadlift": "barbell deadlift",
    "romanian-deadlift": "barbell romanian deadlift",
    "db-romanian-deadlift": "dumbbell romanian deadlift",
    "back-squat": "barbell full squat",
    "front-squat": "barbell front squat",
    "db-goblet-squat": "dumbbell goblet squat",
    "goblet-squat": "kettlebell goblet squat",
    "kb-swing": "kettlebell swing",
    "kb-windmill": "kettlebell windmill",
    "barbell-row": "barbell bent over row",
    "bicep-curl": "0294",  # dumbbell biceps curl -- Forge tags this one `dumbbell`
    "lateral-raise": "dumbbell lateral raise",
    "good-morning": "barbell good morning",
    "glute-bridge": "3013",  # low glute bridge on floor -- Forge tags this one `floor`
    "forward-lunge": "3470",  # forward lunge, bodyweight
    "arnold-press": "dumbbell arnold press",
    "ab-wheel": "wheel rollout",
    # Reviewed against the GIF. "lever back extension" is a loaded machine; Forge's movement
    # is tagged `hyperextension`, which is the unloaded roman chair -- id 0489, not the
    # bench variant that shares its normalised name.
    "back-extension": "0489",
    # "broad jump to vertical" tacks a second, vertical jump onto the end.
    "broad-jump": "forward jump",
    # "lever reverse hyperextension" is a loaded machine. Forge tags this one `bench`, and the
    # catalogue has the unloaded flat-bench version.
    "reverse-hyper": "reverse hyper on flat bench",
    # No alias for the carries. The catalogue's only two-handed carry is "farmers walk", and
    # Forge has no farmer's carry to hang it on -- it has a *suitcase* carry, which is
    # one-sided, and whose entire coaching point is resisting the lean that the second bell
    # removes. Checked the GIF: two dumbbells. Wrong movement, so no picture.
    "hanging-leg-raise": "hanging leg raise",
    "battle-ropes": "battling ropes",
    # No alias for double-unders: the catalogue has only a plain jump rope, and a picture of
    # someone skipping says nothing about the two rope passes that make it a double-under.
    "slam-ball": "medicine ball overhead slam",
    "freestanding-handstand-push-up": "handstand push-up",
    # Same movement, different vocabulary: the catalogue says "lever" for machines.
    "machine-row": "lever seated row",
    # Resolved from the ambiguous list. The catalogue carries several near-variants of each of
    # these and picking one is a judgement, not a match, so they live here where the judgement
    # is visible rather than buried in a scoring function.
    "calf-stretch": "1377",  # calf stretch with hands against wall
    "dip": "chest dip",
    "db-incline-press": "dumbbell incline bench press",
    "db-row": "dumbbell bent over row",
    "db-shoulder-press": "dumbbell seated shoulder press",
    "kb-clean": "kettlebell hang clean",
    "kb-single-arm-floor-press": "kettlebell one arm floor press",
    "kb-row": "kettlebell one arm row",
    "kb-snatch": "kettlebell one arm snatch",
    "leg-curl": "lever lying leg curl",
    "leg-press": "sled 45° leg press",
    "pallof-press": "band horizontal pallof press",
    "seated-cable-row": "cable low seated row",
    "cable-fly": "0227",  # cable standing fly
    "band-curl": "band alternating biceps curl",
    # The kettlebell pass. Twenty-two kettlebell movements had no picture, and the first
    # surprise was that six of them did not need a substitute at all: the catalogue has
    # forty-two kettlebell exercises and the matcher had simply been too cautious. Grip is
    # what it kept getting wrong, so each of these was checked one-armed against two-armed
    # before being written down.
    "kb-front-squat": "0533",  # kettlebell front squat; Forge's is the double, as is this
    "weighted-pistol-squat": "0544",  # kettlebell pistol squat
    "kb-push-press": "0540",  # kettlebell one arm push press; both single-armed
    "kb-press": "0539",  # kettlebell one arm military press; both single-armed
    "kb-gorilla-row": "0522",  # kettlebell alternating row, which is what a gorilla row is
    "kb-floor-press": "0519",  # kettlebell alternating press on floor; two bells, as Forge has
    # Shown with a dumbbell, because the catalogue has no kettlebell version and the movement
    # is identical but for the handle. Every one of these is listed in SHOWN_WITH below, and
    # the app says so under the picture. A substitution nobody is told about is the thing this
    # whole file exists to avoid.
    "kb-deadlift": "0300",  # dumbbell deadlift
    "kb-romanian-deadlift": "1459",  # dumbbell romanian deadlift
    "single-leg-rdl": "1757",  # dumbbell single leg deadlift
    # No alias for the kettlebell walking lunge. It had 0336 for one commit, until the
    # bodyweight pass noticed that 0336 *is* a dumbbell walking lunge and Forge has one of
    # those with no picture. The exact match outranks the substitute, and the same picture
    # cannot serve both without one of them being a lie.
    "kb-reverse-lunge": "0381",  # dumbbell rear lunge; rear and reverse are the same lunge
    "kb-bulgarian-split-squat": "0410",  # dumbbell single leg split squat
    "kb-step-up": "0431",  # dumbbell step-up
    "kb-curl": "0294",  # dumbbell biceps curl
    # The bodyweight and floor pass. Seventy-five movements went in and nine came out, which
    # is the right ratio for a pool this size: the catalogue has 357 bodyweight exercises and
    # almost none of them are the plain version of anything. There is no plank in it, no
    # hollow hold, no bird dog, no v-up that is not banded, and no hanging knee raise that is
    # not either assisted or twisting.
    #
    # Every one of these was opened and looked at. Two of them changed my mind:
    # 2298 is described as lying under a bench and is actually a bar with the feet up on one,
    # and 0865 turns out to be on a bench rather than the floor, which is a surface and not an
    # implement, so it is not flagged as a substitution.
    "smith-squat": "0770",  # smith squat
    "pistol-squat": "1759",  # single leg squat (pistol) male
    "single-leg-glute-bridge": "3645",  # single leg bridge with outstretched leg
    "one-arm-push-up": "0725",  # single arm push-up
    "freestanding-handstand-hold": "3302",  # handstand, kicking up with no wall in shot
    "lat-pulldown": "2330",  # cable lat pulldown full range of motion
    "lying-leg-raise": "0865",  # lying leg-hip raise; on a bench, same movement
    "feet-elevated-inverted-row": "2298",  # inverted row, feet up on a bench
    "db-walking-lunge": "0336",  # dumbbell lunge, stepping forward
    # Banded, because the catalogue has no other kind of either. Listed in SHOWN_WITH.
    "v-up": "1014",  # band v-up
    "bicycle-crunch": "0972",  # band bicycle crunch
}

#: Pictures that show a different implement to the one the movement calls for.
#:
#: The app prints this under the picture. Swapping a dumbbell in for a kettlebell is honest
#: when the movement is the same shape — a rear lunge is a rear lunge whatever is hanging off
#: your hands — and dishonest the moment nobody mentions it, because a person looking up a
#: movement they do not know has no way to tell they are being shown the wrong kit.
#:
#: Which is also why the list is shorter than it could be. A single-arm swing shown two-handed,
#: a front rack lunge shown with the weight at the sides, a bottoms-up press shown any other
#: way: in those the implement *is* the movement, and there is no picture instead.
#: The value names the implement, and the app turns it into a sentence. A new one here needs a
#: matching line in `ExerciseInfoSheet`, which is deliberate: the caption has to be a literal
#: for the translation check to see it, so adding a kit means writing the sentence too.
SHOWN_WITH = {
    "kb-deadlift": "dumbbell",
    "kb-romanian-deadlift": "dumbbell",
    "single-leg-rdl": "dumbbell",
    "kb-reverse-lunge": "dumbbell",
    "kb-bulgarian-split-squat": "dumbbell",
    "kb-step-up": "dumbbell",
    "kb-curl": "dumbbell",
    # The catalogue has no unbanded v-up and no unbanded bicycle crunch. The band is plainly
    # visible in both, anchored at the feet, but the body does the same thing either way and
    # the shape is what somebody opens the picture for.
    "v-up": "band",
    "bicycle-crunch": "band",
}

#: Movements to leave without a picture, whatever the matcher thinks.
#:
#: The opposite of ALIASES, and just as necessary. The catalogue names a near-neighbour close
#: enough to match and the GIF turns out to show a different exercise; without somewhere to
#: record that, the next run puts it straight back.
NO_PICTURE = {
    # "jump box over": jumping sideways *over* a box. A box jump lands on it.
    "box-jump",
    # "band squat row": rowing from the bottom of a deep squat. Different movement.
    "band-row",
    # The only cossack squat in the catalogue is weighted -- which Forge's is not -- and it
    # never shows the standing position, so it demonstrates half the movement.
    "cossack-squat",
    # "pike-to-cobra push-up" flows through cobra, which is a different exercise. The only
    # other pikes in the catalogue are on a stability ball or hanging, and Forge's is on the
    # floor, so there is nothing to swap to.
    "pike-push-up",
    # "wind sprints" is a hanging exercise -- straight-arm hang, legs cycling. Forge's Sprints
    # is running on the ground. Not the same thing at any speed.
    "sprint",
    # The catalogue has only a plain jump rope, and somebody skipping says nothing about the
    # two rope passes that make it a double-under. (It also has "double under jump rope",
    # which does match, so this is a note rather than an entry.)
}

#: The catalogue's equipment vocabulary, as the Forge tags that would satisfy it.
#:
#: Used to *reject* a name match rather than to make one. An entry whose equipment contradicts
#: what the Forge movement needs is a different exercise wearing a similar name. Anything not
#: listed here -- "body weight", "weighted", "assisted" -- says nothing useful either way.
EQUIPMENT_TAGS = {
    "barbell": {"barbell"},
    "olympic barbell": {"barbell"},
    "ez barbell": {"barbell"},
    "trap bar": {"trapBar"},
    "dumbbell": {"dumbbell"},
    "kettlebell": {"kettlebell"},
    "cable": {"cableMachine", "latPulldown", "rowMachine"},
    "smith machine": {"smithMachine"},
    "band": {"resistanceBand", "miniBand"},
    "resistance band": {"resistanceBand", "miniBand"},
    "medicine ball": {"medicineBall", "slamBall", "wallBall"},
    "stability ball": {"stabilityBall"},
    "sled machine": {"sled", "legPress"},
    "wheel roller": {"abWheel"},
    "roller": {"foamRoller"},
}


def normalise(name):
    """Fold the two naming styles together: case, punctuation, parentheticals, plurals."""
    name = name.lower()
    name = re.sub(r"\(.*?\)", " ", name)
    name = re.sub(r"\bv\.?\s*\d+\b", " ", name)
    name = name.replace("-", " ").replace("/", " ")
    name = re.sub(r"[^a-z0-9 ]", " ", name)
    # "v" is not noise. The `v. 2` regex above already removed version markers, and dropping a
    # bare "v" turns "V-Up" into "up", which then matched every pull-up in the catalogue.
    words = [w for w in name.split() if w not in {"male", "female", "version"}]
    words = [w[:-1] if len(w) > 3 and w.endswith("s") and not w.endswith("ss") else w for w in words]
    return " ".join(words)


def forge_exercises():
    """Slug, display name, and equipment tags for every seeded movement."""
    source = io.open(SEED, encoding="utf-8").read()
    out = {}
    for slug, name, kit in re.findall(
        r"(?<![A-Za-z])ex\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*'[^']+'\s*,\s*\[([^\]]*)\]", source
    ):
        out[slug] = (name, set(re.findall(r"'([^']+)'", kit)))
    for _helper, slug, name, kit in re.findall(
        r"(?<![A-Za-z])(cardio|mobility|skill)\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*\[([^\]]*)\]",
        source,
    ):
        out[slug] = (name, set(re.findall(r"'([^']+)'", kit)))
    return out


def load_catalogue(folder):
    """The delivered JSON, whatever it is called this release."""
    names = [f for f in os.listdir(folder) if f.endswith(".json")]
    if not names:
        raise SystemExit(f"No exercise JSON found in {folder}")
    return json.load(io.open(os.path.join(folder, names[0]), encoding="utf-8"))


def equipment_agrees(record, kit):
    """Whether the catalogue entry's equipment is something this Forge movement uses."""
    wanted = EQUIPMENT_TAGS.get(record.get("equipment", "").strip().lower())
    if wanted is None:
        return True
    return bool(wanted & kit)


#: How much evidence each kind of match carries, weakest first.
#:
#: An exact name is a fact. An alias is a judgement somebody already made. "name + equipment"
#: is the machine's own inference, and the only one nobody has looked at -- so it sorts first,
#: because a review that runs out of patience should have spent it on those.
CONFIDENCE = {"name + equipment": 0, "alias": 1, "exact name": 2}


def write_contact_sheet(matched, forge):
    """Every picture beside the movement it was matched to, weakest evidence first."""
    rows = sorted(
        matched.items(),
        key=lambda kv: (CONFIDENCE.get(kv[1][1], 0), forge[kv[0]][0]),
    )

    cards = []
    for slug, (record, how) in rows:
        cards.append(
            f'''  <figure class="card {how.replace(" + ", "-").replace(" ", "-")}">
    <img src="public/exercise-media/{record["id"]}.gif" alt="" loading="lazy">
    <figcaption>
      <strong>{forge[slug][0]}</strong>
      <span class="cat">{record["name"]}</span>
      <span class="meta">{record.get("equipment", "")} &middot; {how}</span>
    </figcaption>
  </figure>'''
        )

    html = f'''<!doctype html>
<meta charset="utf-8">
<title>Forge movement pictures &mdash; review</title>
<style>
  body {{ font: 14px system-ui, sans-serif; margin: 2rem; background: #111; color: #eee; }}
  h1 {{ font-size: 1.3rem; }}
  p.lead {{ color: #aaa; max-width: 60ch; line-height: 1.5; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(190px, 1fr)); gap: 1rem; margin-top: 1.5rem; }}
  .card {{ margin: 0; background: #1b1b1b; border-radius: 10px; overflow: hidden; border-left: 4px solid #444; }}
  .card.name-equipment {{ border-left-color: #fbbf24; }}
  .card.alias {{ border-left-color: #60a5fa; }}
  .card.exact-name {{ border-left-color: #4ade80; }}
  img {{ display: block; width: 100%; background: #fff; }}
  figcaption {{ padding: 0.5rem 0.6rem; display: flex; flex-direction: column; gap: 0.15rem; }}
  .cat {{ color: #bbb; }}
  .meta {{ color: #777; font-size: 0.85em; }}
</style>
<h1>Forge movement pictures &mdash; {len(rows)} matched</h1>
<p class="lead">
  Weakest evidence first. <span style="color:#fbbf24">Amber</span> was inferred from the name
  and the equipment field and nobody has looked at it; <span style="color:#60a5fa">blue</span>
  is an alias somebody chose; <span style="color:#4ade80">green</span> is an exact name match.
  What you are looking for is a picture showing a different movement from the one named on the
  left &mdash; two dumbbells on a one-handed carry, an assisted version of an unassisted lift,
  a seated version of a standing one.
</p>
<div class="grid">
{chr(10).join(cards)}
</div>
'''
    io.open(SHEET, "w", encoding="utf-8", newline=CRLF).write(html)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1

    folder = sys.argv[1]
    copy = "--copy" in sys.argv

    forge = forge_exercises()
    catalogue = load_catalogue(folder)

    by_name, by_id = {}, {}
    for record in catalogue:
        by_name.setdefault(normalise(record["name"]), record)
        by_id[record["id"]] = record

    #: An alias whose slug is not in the seed never matches and never shows up as a gap
    #: either. Cheap to check, and it has already caught three.
    unknown_slugs = sorted(slug for slug in ALIASES if slug not in forge)

    matched, unmatched, alias_misses, ambiguous = {}, [], [], []
    #: An alias is a judgement, not a licence to ignore the equipment. Still applied --
    #: sometimes the right picture uses different kit -- but never silently.
    alias_conflicts = []

    for slug, (name, kit) in sorted(forge.items()):
        if slug in NO_PICTURE:
            unmatched.append((slug, name))
            continue

        alias = ALIASES.get(slug)
        if alias:
            hit = by_id.get(alias) if alias.isdigit() else by_name.get(normalise(alias))
            if not hit:
                alias_misses.append((slug, alias))
            else:
                matched[slug] = (hit, "alias")
                if not equipment_agrees(hit, kit):
                    alias_conflicts.append((slug, name, hit["name"], hit.get("equipment", "")))
            continue

        hit = by_name.get(normalise(name))
        if hit:
            matched[slug] = (hit, "exact name")
            continue

        # The Forge name inside a catalogue name, where the equipment does not contradict it.
        words = set(normalise(name).split())
        candidates = [
            record
            for record in catalogue
            if words
            and words < set(normalise(record["name"]).split())
            and len(set(normalise(record["name"]).split()) - words) <= 2
        ]

        agreeing = [r for r in candidates if equipment_agrees(r, kit)]
        if len(agreeing) == 1:
            matched[slug] = (agreeing[0], "name + equipment")
        elif agreeing:
            # More than one fits. Picking arbitrarily is how a band bench press ends up on a
            # screen that says barbell, so this goes to a person instead.
            ambiguous.append((slug, name, [r["name"] for r in agreeing][:5]))
        else:
            unmatched.append((slug, name))

    lines = [
        "/**",
        " * Forge slug -> ExerciseDB media id.",
        " *",
        " * Generated by `tools/build_exercise_media.py`. Do not edit by hand: add an entry to",
        " * that script's ALIASES table and run it again, so the mapping survives the next time",
        " * the dataset is refreshed.",
        " */",
        "",
        "export const EXERCISE_MEDIA: Record<string, string> = {",
    ]
    for slug, (record, _how) in sorted(matched.items()):
        lines.append(f"  '{slug}': '{record['id']}', // {record['name']}")
    lines.append("};")
    lines.append("")
    lines += [
        "/**",
        " * Where the picture shows a different implement to the one the movement calls for.",
        " *",
        " * The value names the implement; the sheet turns it into a sentence. Rendered under",
        " * the animation, because a substitution nobody is told about is worse than no picture",
        " * at all. Only movements whose shape survives the swap are in here.",
        " */",
        "",
        "export const SHOWN_WITH: Record<string, string> = {",
    ]
    for slug in sorted(SHOWN_WITH):
        if slug in matched:
            lines.append(f"  '{slug}': '{SHOWN_WITH[slug]}',")
    lines.append("};")
    lines.append("")
    io.open(OUT, "w", encoding="utf-8", newline="\r\n").write("\n".join(lines))

    review = [
        "# Movement pictures, for review",
        "",
        f"**{len(matched)} of {len(forge)}** Forge movements have a picture. Names cannot be "
        "trusted on their own, so open each one before it ships — a wrong picture is worse "
        "than none, because nobody looking up an unfamiliar movement can tell.",
        "",
        "Generated by `tools/build_exercise_media.py`.",
        "",
        "## Matched",
        "",
        "| Forge movement | Catalogue entry | Equipment | Matched by |",
        "|---|---|---|---|",
    ]
    for slug, (record, how) in sorted(matched.items(), key=lambda kv: forge[kv[0]][0]):
        review.append(
            f"| {forge[slug][0]} | {record['name']} | {record.get('equipment', '')} | {how} |"
        )

    if ambiguous:
        review += [
            "",
            "## Ambiguous — several entries fit",
            "",
            "Pick one and add it to `ALIASES`, or leave the movement without a picture.",
            "",
            "| Forge movement | Candidates |",
            "|---|---|",
        ]
        for _slug, name, options in sorted(ambiguous, key=lambda r: r[1]):
            review.append(f"| {name} | {', '.join(options)} |")

    review += ["", "## No picture", "", "| Forge movement |", "|---|"]
    for _slug, name in sorted(unmatched, key=lambda r: r[1]):
        review.append(f"| {name} |")
    review.append("")

    os.makedirs(os.path.dirname(REVIEW), exist_ok=True)
    io.open(REVIEW, "w", encoding="utf-8", newline="\r\n").write("\n".join(review))

    if copy:
        os.makedirs(MEDIA, exist_ok=True)
        for existing in os.listdir(MEDIA):
            os.remove(os.path.join(MEDIA, existing))
        copied = 0
        for record, _how in matched.values():
            source = os.path.join(folder, SIZE, f"{record['id']}.gif")
            if os.path.exists(source):
                shutil.copy2(source, os.path.join(MEDIA, f"{record['id']}.gif"))
                copied += 1
        total = sum(os.path.getsize(os.path.join(MEDIA, f)) for f in os.listdir(MEDIA))
        print(f"copied {copied} GIFs into public/exercise-media/ ({total / 1_048_576:.1f} MB)")
        write_contact_sheet(matched, forge)
        print(f"wrote {SHEET}")

    print(f"wrote {OUT}")
    print(f"wrote {REVIEW}")
    print(f"matched {len(matched)} of {len(forge)} Forge movements")
    if unknown_slugs:
        print()
        print(f"ALIASES naming slugs that are not in the seed ({len(unknown_slugs)}):")
        for slug in unknown_slugs:
            print(f"  {slug}")
    if alias_conflicts:
        print()
        print(f"ALIASES whose equipment contradicts the movement ({len(alias_conflicts)}):")
        for slug, name, target, kit in alias_conflicts:
            print(f"  {name} -> {target} [{kit}]")
    if alias_misses:
        print()
        print(f"ALIASES pointing at names not in the catalogue ({len(alias_misses)}):")
        for slug, target in alias_misses:
            print(f"  {slug} -> {target}")
    print()
    print(f"ambiguous, needs a person ({len(ambiguous)})")
    print(f"no picture ({len(unmatched)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
