"""Which seeded movements have no picture, from what actually shipped.

Not to be confused with `exercise_media_gaps.py`, which answered a different question at a
different time: that one guessed, from names alone, what buying the ExerciseDB set would leave
uncovered, and it needs the sample pack's `exerciseList.json` to run at all. This one reads the
two files the app itself reads and reports the truth after the import.

There is no matching to get wrong, because the library reaches a picture two ways and both are
exact. The imported catalogue states the licensed set's id per entry, so every one of those
1,302 movements is illustrated by construction. The curated library was authored here and has
no id, so it is matched by slug through `exerciseMediaMap.ts` — the same two routes
`exerciseMedia.ts` takes at runtime.

Which means every gap is a curated movement, and the reason is always the same: the licensed
set does not have that exercise.

Grouped by movement pattern, since that is how the gaps cluster: nothing in the licensed set
carries a sandbag or drags a sled, so the whole carry shelf is bare, while the pressing and
pulling shelves are nearly full.

    python tools/exercise_media_missing.py
"""

import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
LIBRARY = os.path.join(ROOT, "src", "data", "seed", "exercises.ts")
CATALOGUE = os.path.join(ROOT, "src", "data", "seed", "catalogue.ts")
MEDIA_MAP = os.path.join(ROOT, "src", "data", "exerciseMediaMap.ts")
OUT = os.path.join(ROOT, "docs", "exercise-media-missing.md")

Q = chr(39)
BS = chr(92)
NL = chr(10)

#: `ex(slug, name, pattern, [kit])`, and the cardio and mobility helpers, which take no
#: pattern and so are grouped under their own name instead.
RECORD = re.compile(
    r"(?<![A-Za-z0-9_])(ex|cardio|mobility)\(\s*"
    + Q + r"([a-z0-9-]+)" + Q + r"\s*,\s*"
    + Q + r"((?:[^" + Q + BS * 2 + r"]|" + BS * 2 + r".)*)" + Q
    + r"(?:\s*,\s*" + Q + r"([a-zA-Z]+)" + Q + r")?"
)

MEDIA = re.compile(r"(?m)^\s*" + Q + r"([a-z0-9-]+)" + Q + r"\s*:\s*" + Q + r"([0-9]+)" + Q)

HEADINGS = {
    "squat": "Squat",
    "hinge": "Hinge",
    "lunge": "Lunge",
    "pushHorizontal": "Horizontal push",
    "pushVertical": "Vertical push",
    "pullHorizontal": "Horizontal pull",
    "pullVertical": "Vertical pull",
    "core": "Core",
    "carry": "Carry",
    "gait": "Gait",
    "fullBody": "Full body",
    "cardio": "Cardio",
    "mobility": "Mobility",
}


def strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    return re.sub(r"(?m)^\s*//.*$", "", source)


def library() -> list[tuple[str, str, str]]:
    source = strip_comments(io.open(LIBRARY, encoding="utf-8").read())
    out, seen = [], set()
    for match in RECORD.finditer(source):
        helper, slug, name, pattern = match.groups()
        if slug in seen:
            continue
        seen.add(slug)
        out.append((slug, name.replace(BS + Q, Q), pattern if helper == "ex" else helper))
    return out


def illustrated() -> set[str]:
    source = io.open(MEDIA_MAP, encoding="utf-8").read()
    return {match.group(1) for match in MEDIA.finditer(source)}


def imported_count() -> int:
    """The catalogue entries, which carry their own media id and so are always illustrated."""
    if not os.path.exists(CATALOGUE):
        return 0
    source = io.open(CATALOGUE, encoding="utf-8").read()
    return len(re.findall(r"mediaId: " + Q + r"[0-9]+" + Q, source))


def main() -> int:
    movements = library()
    covered = illustrated()
    imported = imported_count()
    missing = [(slug, name, group) for slug, name, group in movements if slug not in covered]
    total = len(movements) + imported
    lit = len(covered) + imported

    groups: dict[str, list[str]] = {}
    for _slug, name, group in missing:
        groups.setdefault(group, []).append(name)

    order = [k for k in HEADINGS if k in groups] + sorted(set(groups) - set(HEADINGS))

    lines = [
        "# Movements with no picture",
        "",
        f"The library is **{total} movements**: {len(movements)} curated and {imported} imported "
        f"from the licensed catalogue. **{lit}** are illustrated. The **{len(missing)}** below "
        "are not, and every one of them is curated.",
        "",
        "That split is the whole story. Imported movements came from the set that draws them, so "
        "they carry its id and are illustrated by construction. Curated movements were authored "
        "here and have to be matched to a picture by name, which only works when the set has "
        "that exercise at all.",
        "",
        "So the gaps are not scattered, they are whole shelves. Everything that carries, drags "
        "or hangs is bare, as is most of the running, because nobody films a sled push.",
        "",
        "Generated by `tools/exercise_media_missing.py`.",
        "",
    ]
    for group in order:
        names = sorted(groups[group])
        lines.append(f"## {HEADINGS.get(group, group)} ({len(names)})")
        lines.append("")
        lines += [f"- {name}" for name in names]
        lines.append("")

    io.open(OUT, "w", encoding="utf-8", newline=NL).write(NL.join(lines))

    print(f"curated      {len(movements)}")
    print(f"imported     {imported}")
    print(f"illustrated  {lit} of {total}")
    print(f"no picture   {len(missing)}")
    print()
    for group in order:
        print(f"  {HEADINGS.get(group, group):<18} {len(groups[group]):>3}")
    print()
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
