/**
 * Forge slug -> ExerciseDB media id.
 *
 * Generated by `tools/build_exercise_media.py`. Do not edit by hand: add an entry to
 * that script's ALIASES table and run it again, so the mapping survives the next time
 * the dataset is refreshed.
 */

export const EXERCISE_MEDIA: Record<string, string> = {
  'bench-press': '0025', // barbell bench press
};
