/**
 * Forge slug -> ExerciseDB media id.
 *
 * Generated by `tools/build_exercise_media.py`. Do not edit by hand: add an entry to
 * that script's ALIASES table and run it again, so the mapping survives the next time
 * the dataset is refreshed.
 */

export const EXERCISE_MEDIA: Record<string, string> = {
  'ab-wheel': '0857', // wheel rollout
  'air-bike': '0003', // air bike
  'archer-pull-up': '3293', // archer pull up
  'archer-push-up': '3294', // archer push up
  'arnold-press': '2137', // dumbbell arnold press
  'back-extension': '0489', // hyperextension
  'back-squat': '0043', // barbell full squat
  'band-assisted-pull-up': '0970', // band assisted pull-up
  'band-chest-press': '3124', // resistance band seated chest press
  'band-curl': '0968', // band alternating biceps curl
  'band-lateral-raise': '0977', // band front lateral raise
  'band-overhead-press': '1012', // band twisting overhead press
  'barbell-row': '0027', // barbell bent over row
  'battle-ropes': '0128', // battling ropes
  'bear-crawl': '3360', // bear crawl
  'bench-dip': '0129', // bench dip (knees bent)
  'bench-press': '0025', // barbell bench press
  'bicep-curl': '0294', // dumbbell biceps curl
  'bicycle-crunch': '0972', // band bicycle crunch
  'broad-jump': '1472', // forward jump
  'burpee': '1160', // burpee
  'cable-fly': '0227', // cable standing fly
  'calf-stretch': '1377', // calf stretch with hands against wall
  'chest-press-machine': '1301', // machine inner chest press
  'chin-up': '1326', // chin-up
  'db-bench-press': '0289', // dumbbell bench press
  'db-goblet-squat': '1760', // dumbbell goblet squat
  'db-incline-press': '0314', // dumbbell incline bench press
  'db-romanian-deadlift': '1459', // dumbbell romanian deadlift
  'db-row': '0293', // dumbbell bent over row
  'db-shoulder-press': '0405', // dumbbell seated shoulder press
  'db-walking-lunge': '0336', // dumbbell lunge
  'dead-bug': '0276', // dead bug
  'deadlift': '0032', // barbell deadlift
  'decline-push-up': '0279', // decline push-up
  'diamond-push-up': '0283', // diamond push-up
  'dip': '0251', // chest dip
  'double-unders': '3885', // double under jump rope
  'feet-elevated-inverted-row': '2298', // inverted row on bench
  'forward-lunge': '3470', // forward lunge (male)
  'freestanding-handstand-hold': '3302', // handstand
  'freestanding-handstand-push-up': '0471', // handstand push-up
  'front-squat': '0042', // barbell front squat
  'ghr': '3193', // glute-ham raise
  'glute-bridge': '3013', // low glute bridge on floor
  'goblet-squat': '0534', // kettlebell goblet squat
  'good-morning': '0044', // barbell good morning
  'hamstring-stretch': '1511', // hamstring stretch
  'hanging-leg-raise': '0472', // hanging leg raise
  'incline-bench-press': '0047', // barbell incline bench press
  'incline-push-up': '0493', // incline push-up
  'inverted-row': '0499', // inverted row
  'jump-rope': '2612', // jump rope
  'jump-squat': '0514', // jump squat
  'kb-bulgarian-split-squat': '0410', // dumbbell single leg split squat
  'kb-clean': '0535', // kettlebell hang clean
  'kb-curl': '0294', // dumbbell biceps curl
  'kb-deadlift': '0300', // dumbbell deadlift
  'kb-floor-press': '0519', // kettlebell alternating press on floor
  'kb-front-squat': '0533', // kettlebell front squat
  'kb-gorilla-row': '0522', // kettlebell alternating row
  'kb-high-pull': '0548', // kettlebell sumo high pull
  'kb-press': '0539', // kettlebell one arm military press to the side
  'kb-push-press': '0540', // kettlebell one arm push press
  'kb-reverse-lunge': '0381', // dumbbell rear lunge
  'kb-romanian-deadlift': '1459', // dumbbell romanian deadlift
  'kb-row': '0541', // kettlebell one arm row
  'kb-single-arm-floor-press': '1298', // kettlebell one arm floor press
  'kb-snatch': '0542', // kettlebell one arm snatch
  'kb-step-up': '0431', // dumbbell step-up
  'kb-swing': '0549', // kettlebell swing
  'kb-thruster': '0550', // kettlebell thruster
  'kb-windmill': '0554', // kettlebell windmill
  'l-sit': '3419', // l-sit on floor
  'lat-pulldown': '2330', // cable lat pulldown full range of motion
  'lateral-raise': '0334', // dumbbell lateral raise
  'leg-curl': '0586', // lever lying leg curl
  'leg-extension': '0585', // lever leg extension
  'leg-press': '0739', // sled 45° leg press
  'lying-leg-raise': '0865', // lying leg-hip raise
  'machine-row': '1350', // lever seated row
  'mountain-climber': '0630', // mountain climber
  'muscle-up': '0631', // muscle up
  'one-arm-push-up': '0725', // single arm push-up
  'overhead-carry': '4244', // kettlebell overhead carry
  'overhead-press': '0091', // barbell seated overhead press
  'pallof-press': '0979', // band horizontal pallof press
  'pendlay-row': '3017', // barbell pendlay row
  'pistol-squat': '1759', // single leg squat (pistol) male
  'pull-up': '0651', // pull up (neutral grip)
  'push-up': '0662', // push-up
  'renegade-row': '0521', // kettlebell alternating renegade row
  'reverse-hyper': '1423', // reverse hyper on flat bench
  'ring-dip': '0677', // ring dips
  'romanian-deadlift': '0085', // barbell romanian deadlift
  'rope-climb': '0680', // rope climb
  'russian-twist': '0687', // russian twist
  'scapular-pull': '0688', // scapular pull-up
  'seated-cable-row': '0180', // cable low seated row
  'single-leg-glute-bridge': '3645', // single leg bridge with outstretched leg
  'single-leg-rdl': '1757', // dumbbell single leg deadlift
  'sissy-squat': '1489', // sissy squat
  'sit-up': '0735', // sit-up v. 2
  'slam-ball': '1354', // medicine ball overhead slam
  'smith-squat': '0770', // smith squat
  'split-squat': '2368', // split squats
  'sumo-deadlift': '0117', // barbell sumo deadlift
  'thruster': '3305', // barbell thruster
  'trap-bar-deadlift': '0811', // trap bar deadlift
  'turkish-get-up': '0551', // kettlebell turkish get up (squat style)
  'v-up': '1014', // band v-up
  'walking-lunge': '1460', // walking lunge
  'weighted-pistol-squat': '0544', // kettlebell pistol squat
  'weighted-pull-up': '0841', // weighted pull-up
  'weighted-russian-twist': '0846', // weighted russian twist
  'weighted-sit-up': '3670', // weighted decline sit-up
};

/**
 * Where the picture shows a different implement to the one the movement calls for.
 *
 * The value names the implement; the sheet turns it into a sentence. Rendered under
 * the animation, because a substitution nobody is told about is worse than no picture
 * at all. Only movements whose shape survives the swap are in here.
 */

export const SHOWN_WITH: Record<string, string> = {
  'bicycle-crunch': 'band',
  'kb-bulgarian-split-squat': 'dumbbell',
  'kb-curl': 'dumbbell',
  'kb-deadlift': 'dumbbell',
  'kb-reverse-lunge': 'dumbbell',
  'kb-romanian-deadlift': 'dumbbell',
  'kb-step-up': 'dumbbell',
  'single-leg-rdl': 'dumbbell',
  'v-up': 'band',
};
